<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить запись?',
    'Create Employee' => 'Добавить сотрудника',
    'Delete' => 'Удалить',
    'Description' => 'Описание',
    'Employees' => 'Сотрудники',
    'Name' => 'Наименование',
    'NameB' => 'Отдел',
    'NameE' => 'Сотрудник',
    'NameK' => 'Категория',
    'Password' => 'Пароль',
    'Phone' => 'Номер телефона',
    'Remember Me' => 'Запомнить меня',
    'Reset' => 'Отменить',
    'Save' => 'Сохранить',
    'Search' => 'Поиск',
    'TITLE_PROFILE' => 'Личный кабинет',
    'The requested page does not exist.' => 'Запрашиваемая страница не существует',
    'Update' => 'Обновить',
    'User ID' => 'Пользователь',
    'Username' => 'Имя пользователя',
    'AdminPanel' => 'Административная панель',
    'Auth Key' => '',
    'Branch Idbranch' => 'Отдел',
    'Branches' => 'Отделы',
    'Content' => 'Вопрос',
    'ContentN' => 'Содержание новости',
    'Create Branch' => 'Добавить отдел',
    'Create Feedback' => 'Задать вопрос',
    'Create News' => 'Создать новость',
    'Create Newscategory' => 'Создать категорию',
    'Create User' => '',
    'Create Usercontrol' => '',
    'Created At' => 'Дата создания',
    'Created By' => 'Создал',
    'Detail' => 'Детали',
    'Answer' => 'Ответ',

    'Email' => 'Электронная почта',
    'Feedbacks' => 'Обратная связь',
    'ID' => '',
    'Idbranch' => '',
    'Idemployee' => '',
    'Idfeedback' => 'Номер вопроса',
    'Idnews' => '',
    'Idnewscategory' => '',
    'News' => 'Новости',
    'Newscategories' => 'Категории',
    'Newscategory Idnewscategory' => 'Категория',
    'Newsname' => 'Название новости',
    'Password Hash' => '',
    'Password Reset Token' => '',
    'Status' => 'Статус',
    'Update Branch: {name}' => 'Обновить отдел: {name}',
    'Update Employee: {name}' => 'Обновить сотрудника: {name}',
    'Update Feedback: {name}' => 'Обновить вопрос: {name}',
    'Update News: {name}' => 'Обновить новость: {name}',
    'Update Newscategory: {name}' => 'Обновить категорию: {name}',
    'Update User: {name}' => '',
    'Update Usercontrol: {name}' => '',
    'Updated At' => 'Дата обновления',
    'Updated By' => 'Обновил',
    'Usercontrols' => '',
    'Users' => 'Пользователи',
    'Categoryname' => '@@Название категории@@',
    'Date' => '@@Дата@@',
    'EmpName' => '@@ФИО@@',
    'Employee' => '@@Сотрудник@@',
    'Employee Idemployee' => '@@Сотрудник@@',
    'Idaccept' => '@@@@',
    'Idvendor' => '@@@@',
    'Info' => '@@Информация@@',
    'Transporter' => '@@Перевозчик@@',
];
