<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Adress' => 'Адрес',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить запись?',
    'Categoryname' => 'Название категории',
    'Cost' => 'Стоимость',
    'Create Employee' => 'Добавить сотрудника',
    'Create Transporter' => 'Добавить перевозчика',
    'Create Vendor' => 'Добавить поставщика',
    'Date' => 'Дата',
    'Delete' => 'Удалить',
    'Description' => 'Описание',
    'Employee' => 'Сотрудник',
    'Employee Idemployee' => 'Сотрудник',
    'Employees' => 'Сотрудники',
    'Idaccept' => '',
    'Idemployee' => '',
    'Idvendor' => '',
    'Info' => 'Информация',
    'EmpName' => 'ФИО',
    'MaterialName' => 'Наименование материала',
    'StorehouseName' => 'Наименование склада',
    'Name' => 'Наименование',
    'Phone' => 'Номер телефона',
    'Protocolnumber' => 'Номер протокола',
    'Racknumber' => 'Номер стеллажа',
    'Reset' => 'Отменить',
    'Save' => 'Сохранить',
    'Search' => 'Поиск',
    'Storehouse' => 'Склад',
    'Storehouses' => 'Склады',
    'The requested page does not exist.' => 'Запрашиваемая страница не существует',
    'Transporter' => 'Перевозчик',
    'Transporters' => 'Перевозчики',
    'Units' => 'Единицы измерения',
    'Update' => 'Обновить',
    'Password' => 'Пароль',
    'Username' => 'Имя пользователя',
    'Remember Me' => 'Запомнить меня',
    'Update Employee: {name}' => '',
    'TITLE_PROFILE' =>'Личный кабинет',
];
